# Generated by Django 3.0.3 on 2020-02-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200205_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_string', models.CharField(default='DEFAULT DESCRIPTION', max_length=50000)),
            ],
        ),
    ]
